version: "3.8"
services:
  app_bot:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app_bot
    container_name: app_bot
    ports:
      - "5001:5000"
    command: npm run start:dev
    depends_on:
      - redis
    volumes:
      - ./:/usr/local/node-app
    networks:
      - bot

  redis:
    image: "redis:alpine"
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "botredis:/var/lib/redis"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - bot

networks:
  bot:
    driver: bridge

volumes:
  botredis:
    driver: local
